apiVersion: v1
kind: Secret
metadata:
  name: omni-secrets
  namespace: omni
  labels:
    app.kubernetes.io/name: omni
type: Opaque
stringData:
  GITLAB_TOKEN: "<set-gitlab-token>"
  ARGOCD_TOKEN: "<set-argocd-token>"
